// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL1kAOo6eDcN2aLKEW8L8gYWRS0pzOLq4',
    appId: '1:1028677373160:web:f1f6da5ff3b666ed910d5d',
    messagingSenderId: '1028677373160',
    projectId: 'notes-app-b7fcb',
    authDomain: 'notes-app-b7fcb.firebaseapp.com',
    storageBucket: 'notes-app-b7fcb.firebasestorage.app',
    measurementId: 'G-9PP1W9R6NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ukAkuWQgJuoLCsuNZvZrU31a8WA9f2Y',
    appId: '1:1028677373160:android:4ea454d2a413b612910d5d',
    messagingSenderId: '1028677373160',
    projectId: 'notes-app-b7fcb',
    storageBucket: 'notes-app-b7fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaN4nHgqY2EBGm62y8RwK2tqbQ5W_vfw4',
    appId: '1:1028677373160:ios:4cadcb99f9c10309910d5d',
    messagingSenderId: '1028677373160',
    projectId: 'notes-app-b7fcb',
    storageBucket: 'notes-app-b7fcb.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaN4nHgqY2EBGm62y8RwK2tqbQ5W_vfw4',
    appId: '1:1028677373160:ios:4cadcb99f9c10309910d5d',
    messagingSenderId: '1028677373160',
    projectId: 'notes-app-b7fcb',
    storageBucket: 'notes-app-b7fcb.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL1kAOo6eDcN2aLKEW8L8gYWRS0pzOLq4',
    appId: '1:1028677373160:web:6f9f8754cb01a5cd910d5d',
    messagingSenderId: '1028677373160',
    projectId: 'notes-app-b7fcb',
    authDomain: 'notes-app-b7fcb.firebaseapp.com',
    storageBucket: 'notes-app-b7fcb.firebasestorage.app',
    measurementId: 'G-YLCFF3KNN9',
  );
}
